# erzeugt Dienstag, 21. Mai 2019 17:50 (C) 2019 von Leander Jedamus
# modifiziert Montag, 04. Dezember 2023 23:32 von Leander Jedamus
# modifiziert Donnerstag, 10. August 2023 21:20 von Leander Jedamus
# modifiziert Mittwoch, 26. Oktober 2022 10:36 von Leander Jedamus
# modifiziert Montag, 26. September 2022 15:29 von Leander Jedamus
# modifiziert Samstag, 21. November 2020 13:22 von Leander Jedamus
# modifiziert Samstag, 26. September 2020 21:49 von Leander Jedamus
# modifiziert Freitag, 31. Mai 2019 09:32 von Leander Jedamus
# modifiziert Donnerstag, 30. Mai 2019 14:34 von Leander Jedamus
# modifiziert Montag, 27. Mai 2019 12:22 von Leander Jedamus
# modifiziert Sonntag, 26. Mai 2019 12:32 von Leander Jedamus
# modifiziert Mittwoch, 22. Mai 2019 19:01 von Leander Jedamus
# modifiziert Dienstag, 21. Mai 2019 17:52 von Leander Jedamus

RM		    = rm -f
include Makefile.documentation

DOC		    = pyvim.html pyvimldap.html

DOC		    += vim_py_neu.html
DOC		    += vim_ipy_neu.html
DOC		    += vim_py_enter.html
DOC		    += vim_py_geaendert.html
DOC		    += vim_logging_conf_neu.html

DOC		    += vim_pl_neu.html
DOC		    += vim_pl_enter.html
DOC		    += vim_pl_geaendert.html

DOC		    += vim_pm_neu.html
DOC		    += vim_pm_geaendert.html

DOC		    += vim_pas_neu.html
DOC		    += vim_pp_neu.html
DOC		    += vim_pas_enter.html
DOC		    += vim_pas_geaendert.html

DOC		    += vim_java_neu.html
DOC		    += vim_java_enter.html
DOC		    += vim_java_geaendert.html

DOC		    += vim_js_neu.html
DOC		    += vim_js_enter.html
DOC		    += vim_js_geaendert.html

DOC		    += vim_c_neu.html
DOC		    += vim_c_enter.html
DOC		    += vim_c_geaendert.html

DOC		    += vim_lisp_neu.html
DOC		    += vim_lisp_enter.html
DOC		    += vim_lisp_geaendert.html

DOC		    += vim_html_neu.html
DOC		    += vim_html_geaendert.html

DOC		    += vim_cc_neu.html
DOC		    += vim_cc_geaendert.html

DOC		    += vim_h_neu.html
DOC		    += vim_h_geaendert.html

DOC		    += vim_hh_neu.html
DOC		    += vim_hh_geaendert.html

DOC		    += vim_jsp_neu.html
DOC		    += vim_jsp_geaendert.html

DOC		    += vim_f_neu.html
DOC		    += vim_f_geaendert.html
DOC		    += vim_f90_neu.html
DOC		    += vim_f90_geaendert.html

DOC		    += vim_css_neu.html
DOC		    += vim_css_geaendert.html

DOC		    += vim_cob_neu.html
DOC		    += vim_cob_geaendert.html

DOC		    += vim_yacc_neu.html
DOC		    += vim_yacc_geaendert.html

DOC		    += vim_tex_neu.html
DOC		    += vim_tex_geaendert.html

DOC		    += vim_sh_neu.html
DOC		    += vim_zsh_neu.html
DOC		    += vim_sh_geaendert.html

DOC		    += vim_Makefile_neu.html
DOC		    += vim_Makefile_geaendert.html

DOC		    += vim_lex_neu.html
DOC		    += vim_lex_geaendert.html

DOC		    += vim_rb_neu.html
DOC		    += vim_rb_enter.html
DOC		    += vim_rb_geaendert.html

DOC		    += vim_rust_neu.html
#DOC		    += vim_rust_enter.html
DOC		    += vim_rust_geaendert.html

DOC		    += vim_texinfo_neu.html
#DOC		    += vim_texinfo_enter.html
DOC		    += vim_texinfo_geaendert.html

DOC		    += vim_mod_neu.html
DOC		    += vim_mod_enter.html
DOC		    += vim_mod_geaendert.html

DOC		    += vim_def_neu.html
#DOC		    += vim_def_enter.html
DOC		    += vim_def_geaendert.html

all::		    $(DOC)
		    @echo done.

clean:
		    $(RM) $(DOC)

# vim:ai sw=2

