# erzeugt Dienstag, 21. Mai 2019 17:50 (C) 2019 von Leander Jedamus
# modifiziert Mittwoch, 22. Mai 2019 18:09 von Leander Jedamus
# modifiziert Dienstag, 21. Mai 2019 17:52 von Leander Jedamus

RM		    = rm -f
include Makefile.documentation

DOC		    = pyvim.html

DOC		    += vim_py_neu.html
DOC		    += vim_py_enter.html
DOC		    += vim_py_geaendert.html

DOC		    += vim_pl_neu.html
DOC		    += vim_pl_enter.html
DOC		    += vim_pl_geaendert.html

DOC		    += vim_pm_neu.html
DOC		    += vim_pm_geaendert.html

all::		    $(DOC)
		    @echo done.

clean:
		    $(RM) $(DOC)

# vim:ai sw=2

